In [14]:
from ipyparallel import Client
import numpy as np

In [15]:
rc = Client()

In [23]:
@dv.remote(block = True)
def f1(n):
    import numpy as np
    return np.random.rand(n)

[array([0.8561371 , 0.64014332, 0.1728629 , 0.9401165 ]),
 array([0.30411417, 0.85995149, 0.63770501, 0.98306653]),
 array([0.10302651, 0.81523392, 0.20224067, 0.45882809]),
 array([0.79526702, 0.22514021, 0.22676325, 0.81986765]),
 array([0.56101879, 0.41316582, 0.18451767, 0.60635743]),
 array([0.95860948, 0.82813832, 0.31416811, 0.68047375]),
 array([0.46929469, 0.1526248 , 0.26890421, 0.92514905]),
 array([0.44703568, 0.05390347, 0.74524859, 0.75741903]),
 array([0.79318901, 0.28488056, 0.22247258, 0.81340489]),
 array([0.64934123, 0.3511042 , 0.62811953, 0.49439248]),
 array([0.37936254, 0.31418561, 0.66043356, 0.3936062 ]),
 array([0.34765258, 0.15195436, 0.66568807, 0.06396543]),
 array([0.76232968, 0.89578178, 0.3217805 , 0.95545071]),
 array([0.44167215, 0.61790323, 0.89377889, 0.18053821]),
 array([0.92252422, 0.99577144, 0.40101428, 0.3159664 ]),
 array([0.17830831, 0.83737658, 0.75738423, 0.23405151]),
 array([0.66717273, 0.05958274, 0.82378303, 0.57244471]),
 array([0.5804